version: "3"

services:
  db:
    container_name: wealth-management-db
    image: postgres:12
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=wealth_management_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data: { }
